#! /bin/sh

# load machine-local config
if [ -f /etc/xinitrc ]; then . /etc/xinitrc; fi
if [ -f /etc/bspwmrc ]; then . /etc/bspwmrc; fi

# load env
. $HOME/.env

# high compatability wmname
! wmname LG3D

# attach orphaned windows to bspwm
! bspc wm --adopt-orphans

# x config
! xset -dpms
! xset s off
! xsetroot -cursor_name left_ptr
! setxkbmap -option altwin:swap_alt_win

# x daemons
! numlockx&

# sxhkd
pkill sxhkd
! sxhkd -c $XDG_CONFIG_HOME/bspwm/sxhkdrc&

# polybar
#pkill polybar
! polybar&

# picom
! pkill picom
! picom  --experimental-backends --config $XDG_CONFIG_HOME/bspwm/picom.conf&

# themes
! systemctl --user start wallchanger.service
! systemctl --user start wallchanger.timer
! wal -i $XDG_DATA_HOME/backgrounds/"wallpaper-1.*" -n

bspc config focused_border_color "#A01B0D"
bspc config active_border_color "#6B6C6D"
bspc config normal_border_color "#6B6C6D"

export QT_QPA_PLATFORMTHEME=qt5ct

# auth
! /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1&

# bspwm config
bspc config border_width 4
bspc config window_gap   12
bspc config split_ratio  0.5

bspc config focus_follows_pointer true
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config pointer_modifier      mod4

bspc rule -a Screenkey manage=off
