#!/bin/zsh

## zsh
zstyle ':completion:*' menu select

# zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)

autoload -U -z compinit && compinit
zmodload -i zsh/complist

# keybinds
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# prompt
. $XDG_CONFIG_HOME/zsh/prompt.sh

## history
setopt histignorealldups sharehistory
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=$XDG_CACHE_HOME/shell-history

## color
noglob alias ls="ls --ignore='\$??*' --color=tty --group-directories-first"
eval $(dircolors -b $XDG_CONFIG_HOME/dircolors)

alias neofetch="neofetch --ascii_colors 2 15 --colors 15 2 2 2 15"

(cat $XDG_CACHE_HOME/wal/sequences &)
. $XDG_CACHE_HOME/wal/colors-tty.sh

export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

## alias
alias la='ls -a'
alias ll='ls -l'
alias l='ls -CF'
alias tre2="tree -L 2"

alias sudo="sudo "
alias apt="nala"
alias xsudo='pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY'

alias reload-zsh=". $XDG_CONFIG_HOME/zsh/.zshrc"

## tmux
alias tkill="tmux kill-session -t"

alias topen="tmux attach-session -t"
alias tnew="tmux new-session -s"

# tmux in new window
alias topen+="kitty --detach tmux attach-session -t"
function tnew+() {
	if tnew $1 -d; then topen+ $1; fi
}

## zoxide
eval "$(zoxide init zsh)"
alias cd=z
alias cdi=zi

## atuin
eval "$(atuin init zsh)"

## command-not-found
command_not_found_handler() {
	command-not-found $1
	return 127
}

## lesspipe
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
